### ISSUE TITLE
Postgres private schema support

### ISSUE THREAD

**Issue by wesnick** [Romaixn/gosumer#20]
By default Symfony prepends the schema name to the pg_notify channel name with a dot if you are using a schema that is not `public`.  Because of the quoting requirements for postgres it does not seem you can use `TableName` variable interchangeably for channel name.  What I found works is

Table Name: `"myschema"."messenger_messages"`
Channel Name: `"myschema.messenger_messages"`

I have just added a method `func (database PgDatabase) GetChannelName () string` that strips quotes and re-wraps in quotes and it is working for me.

Is there a way to get schemas to work without doing this? If not, I could contribute this back with tests and docs if interesting for you.

**Comment by Romaixn** [comment]
I have never tested it on a private schema, but I believe your solution is quite good! Especially if you haven't found any other alternatives :) Feel free to contribute 🔥
