### ISSUE TITLE
Add parameter to control the number of seconds in the listenEvery function

### ISSUE THREAD

**Issue by Romaixn** [Romaixn/gosumer#6]
Add parameter to control the number of seconds in the listenEvery function called in listen (https://github.com/Romaixn/gosumer/blob/main/pgsql_transport.go#L34) (default to 5 seconds)

**Comment by AshwinKul28** [comment]
Hi, I can take this enhancement

**Comment by Romaixn** [comment]
Thanks 🙏🏻
